### ISSUE TITLE
Import failure publishing a collection with license: ['MIT']

### ISSUE THREAD

**Issue by alikins** [ansible/galaxy#1726]
## Bug Report 
Attempting to publish a collection artifact of  https://github.com/alikins/collection_ntp to https://galaxy-dev.ansible.com results in an import failure:

Invalid collection metadata. Expecting 'license' to be a list of valid SPDX license identifiers, instead found invalid license identifiers: 'MIT' in 'license' value ['MIT']. For more info, visit https://spdx.org"

As far as I can tell, that 'license' being a list with a single 'MIT' entry should be a valid however.

The import record is at https://galaxy-dev.ansible.com/api/v2/collection-imports/12/

The traceback there is:

``` python.traceback
File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/rq/worker.py", line 799, in perform_job
    rv = job.perform()
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/rq/job.py", line 600, in perform
    self._result = self._execute()
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/rq/job.py", line 606, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/galaxy/worker/tasks/collection.py", line 54, in import_collection
    artifact, filename, task_logger)
  File "/usr/share/galaxy/venv/lib64/python3.6/site-packages/galaxy/worker/tasks/collection.py", line 83, in _process_collection
    raise exc.ImportFailed(str(e))
```

The galaxy.yml is:

``` yaml
namespace: alikins
name: collection_ntp
version: 0.1.166
license:
  - MIT
description: NTP installation and configuration for Linux.
repository:
documentation:
homepage:
issues:
authors:
  - geerlingguy
tags:
  - system
  - ntp
  - date
  - time
  - timezone
readme: "README.md"
dependencies: {}
```

##### EXPECTED RESULTS

As far as I can tell, that 'license' being a list with a single 'MIT' entry should be a valid.

**Comment by alikins** [comment]
ping @awcrosby

**Comment by chouseknecht** [comment]
Seeing the same thing with `GPL-3.0-or-later`.

Here's the error returned from the import `https://galaxy-dev.ansible.com/api/v2/collection-imports/15/`:

```
Invalid collection metadata. Expecting 'license' to be a list of valid SPDX license identifiers, instead found invalid license identifiers: 'GPL-3.0-or-later' in 'license' value ['GPL-3.0-or-later']. For more info, visit https://spdx.org
```

Here's my `MANIFEST.json` file:

```
{
    "collection_info": {
        "license": [
            "GPL-3.0-or-later"
        ],
        "name": "bcoca_collection",
        "repository": "https://github.com/bcoca/collection.git",
        "tags": [
            "foo",
            "bar"
        ],
        "documentation": null,
        "namespace": "chouseknecht",
        "version": "0.0.1",
        "dependencies": {},
        "authors": [
            "Chris Houseknecht house@redhat.com"
        ],
        "readme": null,
        "license_file": null,
        "homepage": null,
        "issues": "https://github.com/bcoca/collection/issues",
        "description": "This is a test collection."
    },
    "file_manifest_file": {
        "format": 1,
        "ftype": "file",
        "chksum_sha256": "ec8e87eafa5d0fce636813f1b2b6a24b48fe767b3de11fd177a5cac8cf51bcda",
        "name": "FILES.json",
        "chksum_type": "sha256"
    },
    "format": 1
}
```

**Comment by awcrosby** [comment]
The issue seems to occur on galaxy-dev, but works ok on the local development environment. It is likely the returning of the cached valid licenses obtained from `spdx_licenses.json` https://github.com/ansible/galaxy/blob/devel/galaxy/importer/utils/spdx_licenses.py#L31 is blank or wrong, but I haven't been able to debug inside galaxy-dev to confirm.

**Comment by awcrosby** [comment]
Resolved with #1731

**Comment by anshulbehl** [comment]
I am facing the same issue:

> [abehl@ansh collection_demo]$ mazer migrate_role --role ~/.ansible/roles/victorock.gce_config/ --output-dir ./roles/victorock.gce_config --namespace anshulbehl --version=1.0.0
> WARNING| The value for "license" found in "/home/abehl/.ansible/roles/victorock.gce_config/" is "MIT" which is not a valid SPDX license
> WARNING| The value provided by --license is "None" which is not a valid SPDX license
> Invalid collection metadata. Expecting 'license' to be a list of valid SPDX license identifiers, instead found invalid license identifiers: 'MIT' in 'license' value ['MIT']. For more info, visit https://spdx.org

The action above is local and I am trying to push anything to galaxy yet, however is still fails to migrate roles to a collection that I am trying to make.
Please advise

**Comment by awcrosby** [comment]
@anshulbehl `mazer migrate_role` is independent of the galaxy server, please report this over on https://github.com/ansible/mazer, thanks!
