### ISSUE TITLE
Namespace rename issue

### ISSUE THREAD

**Issue by stroobl** [ansible/galaxy#2028]
##### Github Org Link
https://github.com/fiaasco

##### Admins
stroobl
dverhelst

Hi, we removed the camelcase from our github org name (FiaasCo -> fiaasco) since this was not really what we want for galaxy roles and we are adding new roles. The github part went fine, but on galaxy it doesn't work as expected. I can't add the new namespace and I also can no longer import all roles in the old namespace (some imports fail, probably due to the github redirect).
Could you completely remove the FiaasCo namespace and import fiaasco so that we can replace everything?

Sorry for the inconvenience.

**Comment by chouseknecht** [comment]
Done. Let us know, if you run into any additional problems.

**Comment by stroobl** [comment]
Thanks, but I don't think the problem is fully resolved. The old provider namespace is gone from my list now, but when I import the new one I still get:
"Error! Error creating or updating provider namespaces: get() returned more than one ProviderNamespace -- it returned 9! (undefined) "

**Comment by dverhelst** [comment]
@chouseknecht , I have the exact same issue when adding the fiaasco namespace to my Ansible Galaxy for importing.
![Screenshot_2019-10-19_at_13_57_17](https://user-images.githubusercontent.com/486948/67144656-2b201c00-f279-11e9-828c-4dbd2f784b31.png)

Do  you want me to open up a new bug for this?
Please advise.
