### ISSUE TITLE
Ansible Galaxy import fails with permission denied (no namespace available?)

### ISSUE THREAD

**Issue by jschaul** [ansible/galaxy#2238]
##### SUMMARY

I am not able to import to galaxy via command line, nor via the web interface.

On terminal, I get a cryptic "permission denied" and on the web interface, under "My content" there is no single namespace (documentation states that there *should* be always at least one). Similarly, "My imports" is empty.

##### STEPS TO REPRODUCE

```
ansible-galaxy import jschaul ansible-cassandra -v
ERROR! Permission denied.
```
##### EXPECTED RESULTS

Something other than an error; or at least an error with enough information to do something about.

##### ACTUAL RESULTS

![myImports](https://user-images.githubusercontent.com/2112744/74269791-5936d980-4d0a-11ea-9b96-80558e95bbf2.png)
![myContent](https://user-images.githubusercontent.com/2112744/74269792-59cf7000-4d0a-11ea-9009-9ae4ec187ff7.png)

```

```

**Comment by chouseknecht** [comment]
You were not assigned as the owner of the namespace. Should be fixed now.

**Comment by jschaul** [comment]
Hi, thanks for trying to fix this issue. Unfortunately, the issue remains, nothing has changed from my view. When I log in, I'm logged in as `joe.schaul` (even though my github username is `jschaul`). I still cannot see any content under "my imports" and "my content" and I still cannot upload something via the terminal.
