### ISSUE TITLE
namespace: w3f

### ISSUE THREAD

**Issue by fgimenez** [ansible/galaxy#2284]
## Namespace Request
Namespace: w3f

##### Description
We would like to use w3f galaxy namespace for uploading content using w3fbot account.

##### GitHub Org Link
https://github.com/w3f

##### Admins
w3fbot
pampatzoglou
fgimenez

**Comment by chouseknecht** [comment]
Done

**Comment by fgimenez** [comment]
@chouseknecht thanks for looking into it but we are still not able to associate the w3f provider namespace with the w3f galaxy namespace, we still get `Error! This provider namespace is already associated with a Galaxy namespace (w3f)` when trying to do so. Because of this we are not able to upload roles from github. 

Is there anything else missing on our side? Thanks!

**Comment by gundalow** [comment]
@fgimenez Hi
1) Are you publishing a collection or a role
2) What method are you using to public ie `ansible-galaxy collection publish` or via GitHub UI?

**Comment by fgimenez** [comment]
hi @gundalow 

> 1. Are you publishing a collection or a role

This role https://github.com/w3f/polkadot-module-benchmarking

> 2\. What method are you using to public ie `ansible-galaxy collection publish` or via GitHub UI?

I'm trying `ansible-galaxy role import` with the w3fbot github user, we would like to be able to import roles directly from github using the command line. These are the commands and output:
```
$ ansible-galaxy login --github-token=$GITHUB_BOT_TOKEN
Successfully logged into Galaxy as w3fbot
$ ansible-galaxy role import w3fbot w3f/polkadot-module-benchmarking -vvvvvvv
ansible-galaxy 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/fgimenez/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fgimenez/.local/lib/python3.6/site-packages/ansible
  executable location = /home/fgimenez/.local/bin/ansible-galaxy
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
Using /etc/ansible/ansible.cfg as config file
Initial connection to galaxy_server: https://galaxy.ansible.com
Opened /home/fgimenez/.ansible/galaxy_token
Calling Galaxy at https://galaxy.ansible.com/api/
Found API version 'v1, v2' with Galaxy server default (https://galaxy.ansible.com/api/)
Calling Galaxy at https://galaxy.ansible.com/api/v1/imports/
Successfully submitted import request 599936
Calling Galaxy at https://galaxy.ansible.com/api/v1/imports?id=599936
Starting import: task_id=599936, repository=w3fbot/w3f/polkadot-module-benchmarking
 
Task "599936" failed: 404 {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3'}
```

**Comment by chouseknecht** [comment]
@fgimenez 
You need to log into Galaxy. Go to My Content, and for the `w3f` namespace, choose the Edit Properties menu option. On the properties page, associate the provider namespace (i.e. the GitHub namespace containing the role repository). See https://galaxy.ansible.com/docs/contributing/namespaces.html#adding-github-organizations-to-a-namespace

**Comment by fgimenez** [comment]
@chouseknecht thanks for your response, what you propose is what we have been trying and we get this error `Error! This provider namespace is already associated with a Galaxy namespace (w3f)` (see comment above of Mar 27 https://github.com/ansible/galaxy/issues/2284#issuecomment-604924440). 

I've attached a screenshot showing how the Edit properties form looks like when we get the error.
![Screenshot_2020-05-14_14-41-32](https://user-images.githubusercontent.com/70376/81935670-4f669000-95f1-11ea-81e0-996878fd3170.png)

**Comment by chouseknecht** [comment]
It's currently associated with namespace `pampatzoglou`

**Comment by chouseknecht** [comment]
I moved it from `pampatzoglou` to `w3f` in Galaxy. Let's see if that fixes your import.

**Comment by fgimenez** [comment]
worked like a charm, thanks a lot @chouseknecht !!!
