### ISSUE TITLE
Recurrent failure of role imports on ansible galaxy since approx Apr.22

### ISSUE THREAD

**Issue by Voronenko** [ansible/galaxy#2362]
##### SUMMARY

Seems since 22 of april there is misconfiguration on galaxyansible.com 
in particular all role imports are failing with message like

```
Starting import: task_id=617749, repository=NAMEOFREPO
Task "617749" failed: Failed to get GitHub account for Galaxy user galaxytasks01. You must first authenticate with GitHub. 
```
seems configuration issue

Affects all of the roles imports since that date.

```
Starting import: task_id=617824, repository=softasap/sa-acme-sh 
 
Task "617824" failed: Failed to get GitHub account for Galaxy user galaxytasks01. You must first authenticate with GitHub. 
```

**Comment by Voronenko** [comment]
@chouseknecht any hints? Also, do anyone else have the same issue, or it is just mine account?

**Comment by chouseknecht** [comment]
I just imported a role without any issue, so it doesn't seem to be widespread. Just based on the error message, I would suggest logging into the galaxy.ansible.com website. That should refresh your OAuth token.

**Comment by Voronenko** [comment]
@chouseknecht  Thanks! 
Side note: that I had to re-login from a completely clean session, as just logoff/logon to galaxy.ansible.com was not leading to fixing the imports.
Perhaps makes sense either to make error message more clear, to detect it and propose logged-in user to refresh token from UI.

**Comment by Voronenko** [comment]
@chouseknecht  Sorry have to reopen issue.

Recent import: tadamm:

```
Starting import: task_id=618926, repository=softasap/sa-gluster-fs 
 
Task "618926" failed: Failed to get GitHub account for Galaxy user galaxytasks01. You must first authenticate with GitHub. 
```

Quite short time passed to consider that situation is OK, nope ?

**Comment by Voronenko** [comment]
Side information:

roles are on a public repositories.

If travis run succeeds, galaxy is asked to re-import role using webhook as per   https://galaxy.ansible.com/docs/contributing/importing.html

```yaml
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
```

https://github.com/softasap/sa-box-jenkins/blob/master/.travis.yml#L48

Again, I observe issues starting from 22 april 2020, before that there were no major issues for 3+ previous years

**Comment by Voronenko** [comment]
@cutwater @chouseknecht perhaps anything changed on pinging ansible galaxy via notification from travis pipeline?
Some new requirements to ?

seems @chouseknecht advise does not affect travis builds notifications - all imports are failed.
And it is quite annoying to re-click manual import in galaxy UI for those roles.

```yaml
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
```
==>
```
Starting import: task_id=618926, repository=XXX
 Task "618926" failed: Failed to get GitHub account for Galaxy user galaxytasks01. You must first authenticate with GitHub. 
```

I do not observe anything new in section

https://galaxy.ansible.com/docs/contributing/importing.html#import-roles-via-travis-ci

**Comment by Voronenko** [comment]
April 29: remains: import pinged from travis pipeline miserably fails

```
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
```

clicking manual "import" in the galaxy UI works.

Any hints, how import of roles via travis ci should now be configured, @cutwater @chouseknecht ?

**Comment by bittner** [comment]
Same here, my imports are continuously failing when triggered from [Travis CI via GitHub using a webhook](https://github.com/painless-software/ansible-role-software/blob/master/.travis.yml), just like mentioned above. The log of the failed import says:
```json
Starting import: task_id=620940, repository=painless-software/ansible-role-software 
 
Task "620940" failed: 401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'} 
```
A subsequently manually triggered import then works.

I didn't find an option to update my credentials (GitHub token?) on the Galaxy UI. This probably needs to be done by removal of the authorization on GitHub?

**Comment by chouseknecht** [comment]
The auth model has not changed. We fixed the `galaxytasks01` user account, so that should take care of the issue @Voronenko reported.

**Comment by tobias-richter** [comment]
@chouseknecht we are also experiencing this issue on nearly all of our roles e.g.
``` 
Task "621866" failed: 401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'} 
```

Role: wcm_io_devops.jenkins_service

so from my perspective this is not fixed.

**Comment by Voronenko** [comment]
One of my roles just failed as well from travis pipeline

```
Starting import: task_id=621757, repository=softasap/sa-gitlab-runner 
 
Task "621757" failed: 401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'} 
```
