### ISSUE TITLE
Namespace request: kubeinit

### ISSUE THREAD

**Issue by ccamacho** [ansible/galaxy#2487]
## Namespace Request
Namespace: kubeinit

##### Description
KubeInit provides Ansible playbooks and roles for the deployment and configuration of multiple Kubernetes distributions. The main goal of KubeInit is to have a fully automated way to deploy in a single command a curated list of prescribed architectures.

##### GitHub Org Link
https://github.com/Kubeinit/

##### Admins
ccamacho

**Comment by thedoubl3j** [comment]
done @ccamacho :) 

If you all are interested in becoming an Ansible Partner, you can visit https://www.ansible.com/partners for more information. If this seems interesting to you all, please feel free to reach out to us here in the comments. Otherwise, let us know if any issues arise with the namespace, cheers.

**Comment by ccamacho** [comment]
Hi @thedoubl3j thanks for the update, but I still can't see the namespace created in Galaxy.

**Comment by thedoubl3j** [comment]
I am seeing it here https://galaxy.ansible.com/kubeinit it should be showing up under my content
