### ISSUE TITLE
Open in new window does not work for next galaxy

### ISSUE THREAD

**Issue by akaRem** [ansible/galaxy#744]
##### STEPS TO REPRODUCE

Go to https://galaxy-qa.ansible.com/search?platforms=EL&order_by=-relevance&page_size=100

Right click on role - no option to open in new window.
CMD+click -> role opens in the same window.

##### EXPECTED RESULTS

it's possible to open role/user details and other stuff in new tab.

This is very important because galaxy is flooded with forks of the same role and you often want to compare the most popular, drop those which are just duplicates and then compare difference.

##### ACTUAL RESULTS

```

```

**Comment by cognifloyd** [comment]
I asked the following in #ansible-galaxy on irc.
```
(12:12:49) cognifloyd: Maybe I'm missing something: When searching in the new galaxy layout, how can I open roles in a new tab?
(12:41:22) chouseknecht: Cognifloyd: click on the role name, right click to pick new tab option
(12:44:55) cognifloyd: So, I do have to click first and then open in a new tab. Bummer.
(12:45:00) ***cognifloyd goes to file a feature request.
(12:45:35) cognifloyd: https://github.com/ansible/galaxy/issues/744
```

I don't like going into a role and then hitting back to get to the search list.
1. This is extra work for a pretty standard web feature (open link in new tab).
2. When hitting back to return to the search results, the results list is back at the top of the page, not where I left off near the bottom.

BTW I like the revamped look and feel, it just needs a few more UX touches to have a smooth search experience.

**Comment by chouseknecht** [comment]
Fixed by #833

**Comment by akaRem** [comment]
@chouseknecht Is it deployed? 
It's still reproducible on https://galaxy.ansible.com
I can open author details in new tab, but not role.

**Comment by cutwater** [comment]
@akaRem no, it's not deployed.
Reopening this issue and adding `status/fix-committed`
