### ISSUE TITLE
Installing roles with dashes in the name is broken

### ISSUE THREAD

**Issue by elliotweiser** [ansible/galaxy#775]
##### SUMMARY

I used to be able to install roles with dashes in the name, e.g. [elliotweiser.osx-command-line-tools](https://galaxy.ansible.com/elliotweiser/osx-command-line-tools). I can no longer do so. It appears that underscores are required. _This breaks roles and playbooks that pull in such roles as dependencies._ 

Example: https://travis-ci.org/geerlingguy/mac-dev-playbook/builds/398684539

##### STEPS TO REPRODUCE

```
pip install ansible # occurs w/ 2.6 and 2.5
ansible-galaxy install elliotweiser.osx-command-line-tools
```

##### EXPECTED RESULTS

The role should be successfully downloaded.

##### ACTUAL RESULTS

```
$ ansible-galaxy install elliotweiser.osx-command-line-tools
- downloading role 'osx-command-line-tools', owned by elliotweiser
 [WARNING]: - elliotweiser.osx-command-line-tools was NOT installed successfully: - sorry, elliotweiser.osx-command-line-tools was not
found on https://galaxy.ansible.com.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

It appears the role can only be installed when using underscores instead of dashes:

```
$ ansible-galaxy install elliotweiser.osx_command_line_tools
- downloading role 'osx_command_line_tools', owned by elliotweiser
- downloading role from https://github.com/elliotweiser/ansible-osx-command-line-tools/archive/2.1.0.tar.gz
- extracting elliotweiser.osx_command_line_tools to /Users/elliotweiser/git/github/elliotweiser/elliotweiser.osx_command_line_tools
- elliotweiser.osx_command_line_tools (2.1.0) was installed successfully
```

I'm not sure if this was change in behavior was intentional, but it may have been an oversight.

**Comment by elliotweiser** [comment]
Some additional irony...

This URL looks good :+1: https://galaxy.ansible.com/elliotweiser/osx-command-line-tools

This one, not so much... https://galaxy.ansible.com/elliotweiser/osx_command_line_tools

**Comment by chouseknecht** [comment]
Related to #776

**Comment by chouseknecht** [comment]
In local development, I am able to see in the Debug logging that a new Content record is being created when one clearly should have already existed:

```
2018-07-01 03:33:13,502 INFO tasks: Starting task: 256196
[2018-07-01 03:33:13,502: INFO/Worker-3] Starting task: 256196
2018-07-01 03:33:15,925 DEBUG base: name: osx-command-line-tools
[2018-07-01 03:33:15,925: DEBUG/Worker-3] name: osx-command-line-tools
2018-07-01 03:33:15,930 DEBUG base: original_name: ansible-osx-command-line-tools
[2018-07-01 03:33:15,930: DEBUG/Worker-3] original_name: ansible-osx-command-line-tools
2018-07-01 03:33:15,953 DEBUG base: Created new Content instance: id=26513, content_type="role", name="None"
[2018-07-01 03:33:15,953: DEBUG/Worker-3] Created new Content instance: id=26513, content_type="role", name="None"
```

**Comment by elliotweiser** [comment]
I wonder if this explains why my role :point_up: received a new ID after the 3.0.0 upgrade.

https://github.com/elliotweiser/ansible-osx-command-line-tools/commit/4db0cef508ca6822c2a29fac86c0a98ff7241619

**Comment by chouseknecht** [comment]
@elliotweiser 

Fixed by #784. You can test your role at https://galaxy-qa.ansible.com - our QA site, where your role is still named 'osx-command-line-tools'

The patch will be deployed to production tomorrow morning. Let us know, if you want to rename your role in production.

**Comment by elliotweiser** [comment]
Confirmed:

```
$ ansible-galaxy install elliotweiser.osx-command-line-tools -s https://galaxy-qa.ansible.com -p roles
- downloading role 'osx-command-line-tools', owned by elliotweiser
- downloading role from https://github.com/elliotweiser/ansible-osx-command-line-tools/archive/2.1.0.tar.gz
- extracting elliotweiser.osx-command-line-tools to roles/elliotweiser.osx-command-line-tools
- elliotweiser.osx-command-line-tools was installed successfully
```

Thanks for the offer, but I'd rather keep the original name, i.e. `osx-command-line-tools` (w/ dashes). I can revert the changes I made in response as needed.

**Comment by chouseknecht** [comment]
@cutwater 

After deploying 3.0.1 tomorrow morning, please update the Content record for elliotweiser.osx-command-line-tools, replacing '_' with '-' in name.

**Comment by robertdebock** [comment]
Thanks for pushing the latest release.

I'm still seeing [an issue](https://galaxy.ansible.com/my-imports?namespace=robertdebock&repository_name=python_pip&selected=259026&page_size=10):
```

INFO Starting import: task_id=259026, repository=robertdebock/ansible-role-python-pip
WARNING [role] 'py-pip' is not a valid tag. Tags must container lowercase letters and digits only. Skipping.
INFO [role] Linting...
INFO [role] Linting OK.
Task "259026" failed: duplicate key value violates unique constraint "main_content_namespace_id_repository__d7de6a83_uniq" DETAIL: Key (namespace_id, repository_id, name, content_type_id)=(4003, 53998, python_pip, 11) already exists.
```

**Comment by chouseknecht** [comment]
@robertdebock 

Think it was a timing issue. Re-imported `robertdebock/ansible-role-python-pip`, and it succeeded. 

Let us know, if you want your roles restored to '-'. I see some of them had '-' converted to '_'.

**Comment by cutwater** [comment]
@elliotweiser `osx-command-line-tools` is fixed.

**Comment by chouseknecht** [comment]
Looks like repo names are still getting renamed. Pushing #806 to [QA](https://galaxy-qa.ansible.com) for testing.

**Comment by stefano-m** [comment]
This is very bad. User names were also changed with no notice whatsoever. See also #779 

This has broken a bunch of role installs from requirements files and more importantly broken trust with ansible galaxy.

As a user who wants to install a role **that used to work fine**, how do you think I would react to the following message (using my own insignificant role as an example)?

```
[WARNING]: - stefano-m.iptables was NOT installed successfully: - sorry, stefano-m.iptables was not found on https://galaxy.ansible.com.
```

At this point I would expect that the hyphenated names are restored and **both** the hyphenated and underscored namespaces and packages are linked to the **same** user.

@chouseknecht  I appreciate that you are trying hard to solve the issue. Thanks for working on this.

**Comment by robertdebock** [comment]
@chouseknecht thanks, I'd like to have these roles restored with a "-" instead of "_":
- ansible-role-digitalocean-agent
- ansible-role-python-pip
- ansible-role-sudo-pair

It seems this is something that I can't do right? Otherwise, I'd like to be able to do this myself.

**Comment by chouseknecht** [comment]
@robertdebock 
Before we do that, remove 'role_name' from the `meta/main.yml` file of each role. Otherwise, it'll just translate '-' to '_' again on the next import.

**Comment by chouseknecht** [comment]
@elliotweiser 

Same as mentioned above, if you put 'role_name' in your metadata, please remove it, and then we can reset the role and repo names, and it should be good.

**Comment by chouseknecht** [comment]
@lae

Same as mentioned above, if you put 'role_name' in your metadata, please remove it, and then we can reset the role and repo names, and it should be good.

**Comment by lae** [comment]
@chouseknecht reverted

**Comment by chouseknecht** [comment]
@lae 

Your *travis-lxc* roles is fixed now. As a test, I re-imported after the change, and both the repo and content name remain as 'travis-lxc'.

**Comment by robertdebock** [comment]
I've renamed my roles to use underscores instead of dashes. Thanks for your support @chouseknecht

**Comment by spk83** [comment]
@chouseknecht could you please fix andrewrothstein.alpine-glibc-shim and andrewrothstein.java-oracle as well?

**Comment by chouseknecht** [comment]
@spk83 done!

**Comment by paulfantom** [comment]
I have the same issue with:
- cloudalchemy.node-exporter
- cloudalchemt-mysqld-exporter
- cloudalchemy.snmp-exporter
- cloudalchemy.blackbox-exporter

None of above have `role_name` in metadata. Can you reimport it with `-` instead of `_`?

**Comment by chouseknecht** [comment]
@paulfantom 

Updated all except cloudalchemy.mysqld-exporter. Don't see that one in Galaxy. Import it, and I'll update it.

**Comment by chouseknecht** [comment]
@paulfantom 

That last one is fixed. It's now 'mysqld-exporter'.

Going forward, anything new will have '-' converted to '_'. 

If you want to alter the name (e.g., remove 'ansible-'), then use the `role_name` attribute to set the name.

Deleting a role and re-importing, or setting `role_name` value, will update the name in the Galaxy database, and cause '-' to be converted to '_'.

**Comment by geerlingguy** [comment]
@chouseknecht - Found another one that I missed earlier: https://galaxy.ansible.com/geerlingguy/ssh-chroot-jail — can it be reverted to use `-` instead of `_`?

**Comment by chouseknecht** [comment]
@geerlingguy 

https://galaxy.ansible.com/geerlingguy/ssh-chroot-jail is fixed.

Sorry for the delay. Didn't see your comment until now.

**Comment by chouseknecht** [comment]
Closing, as I think we've renamed all the roles listed on this issue.

If you find more roles that you want renamed from '_' to '-', please open a new issue, so that we don't miss it.

**Comment by danielkucera** [comment]
Not sure if this one is a similar case: 
https://galaxy.ansible.com/mattfinlayson/ansible-consul

**Comment by andrewrothstein** [comment]
@chouseknecht can u fix the mapping of my roles below into the galaxy?
andrewrothstein.ansible-openjdk -> andrewrothstein.openjdk
andrewrothstein.ansible_restic -> andrewrothstein.restic
thanks!
